version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/apps/piano-tool/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/apps/piano-tool"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/apps/piano-tool/android"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
