[pytest]
pythonpath = .
filterwarnings =
    error
    ignore::UserWarning
    ignore::starlette.exceptions.StarletteDeprecationWarning
    ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning
